### ISSUE TITLE
Design Inspector shiny

### ISSUE THREAD

**Issue by nfultz** [DeclareDesign/shiny#6]
**Design:**
- [x] wireframing

**Dev:**

Part 1. Select design.
- [ ] Option to select:
  - [ ] from designs in a library [ suggest we start with this, but add below before demo: ]
    - [x] Two Arm
    - [ ] p arm
    - [x] Two way factorial
    - [x] library diagnoses should be precomputed
      - [x] disable diagnosis ui in this case
  - [x] Option to load a design from a local drive
  - [x] or a URL to a design.
    - [ ] or DOI

Part 2. Create Query
- [x] Prints list and description of changeable options
- [x] Allows diagnosis of altered designs, ie altered by user
- [x] Allows printouts of altered designs

Part 2. Summarize
- [x] Print `summary.design`
  - [x] Pretty print to html/latex 
- [x] bibliographic citation (using the existing `cite_design` function)
- [x] Diagnostics (print the diagnosis df)
- [ ] Power curve #10 
- [x] Print code of design
  - [x] and download

For query design, eventually we will use the new modifiable/variable arguments in declare_design. For now, if that seems a bit further off, we can use a template function for same purpose i.e. 

```
design_template <- function(N, arms){
  ...
  return(design)
}
```

Part 4. Use designs (less important)
- [x] Print simulated data
- [ ] Implement assignment [suggest we hold to version 2, right now this is not possible]
- [ ] Upload data and Implement analysis given uploaded data [suggest we hold to version 2, right now this is not possible]

Part 5
- [x] Export modified design

*1 to 3 are most important.* Ideal visual is not just lots of tabs but a dashboard feel where you control things at the top and see output below

Ideal demo does this for 2 to 3 basic designs sitting in a library. Could all be very simple ones eg all 2 arm designs with different default parameter values or different choice of estimators. Ideally named for studies that they correspond to.

**Testing/QA:**

- [ ] `testthat`
- [ ] `shinytests`
- [ ] `R CMD check --as-cran`

**Comment by nfultz** [comment]
Super old, will start a new ticket.
